---
driver:
  name: vagrant
  gui: true

provisioner:
  name: salt_solo
  salt_install: bootstrap
  formula: windows
  require_chef: false
  init_environment: |
    Clear-Host
    # write-host "RUNNING ME NOW"
    # if ( Test-Path -Path $env:TEMP\..\kitchen\ -PathType Container ) { Remove-Item "$env:TEMP\..\kitchen\" -Recurse -Force }
    $AddedLocation ="c:\salt"
    $Reg = "Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment"
    $OldPath = (Get-ItemProperty -Path "$Reg" -Name PATH).Path
    $NewPath= $OldPath + ’;’ + $AddedLocation
    Set-ItemProperty -Path "$Reg" -Name PATH –Value $NewPath
  state_top:
    base:
      '*':
        - windows

platforms:
  # Windows 10, version 1903 (OS Build: 18362.592)
  - name: windows-10-1903
    driver:
      box: StefanScherer/windows_10
      box_version: 2020.01.15

verifier:
  name: inspec
  windows: true
  run_destructive: true
  reporter:
    - cli
  inspec_tests:
    - path: test/integration/default

suites:
  - name: py3
    provisioner:
      salt_bootstrap_options: "-version 2019.2.3 -pythonVersion 3"