
os: windows
language: shell
# rvm:
#  - 2.6.5

services: docker
sudo: true
env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    # - KITCHEN_YAML=.kitchen.travis.yml
    - KITCHEN_LOCAL_YAML=.kitchen.proxy.yml

# # blocklist
# branches:
#   except:
#   - legacy
#   - experimental

# safelist
branches:
  only:
  - master
  - stable

# install:
#   - choco install vim
# before_install:
# - |-
#     case $TRAVIS_OS_NAME in
#       windows)
#         [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
#         choco uninstall -y mingw
#         choco upgrade --no-progress -y msys2
#         export msys2='cmd //C RefreshEnv.cmd '
#         export msys2+='& set MSYS=winsymlinks:nativestrict '
#         export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
#         export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
#         export msys2+=" -msys2 -c "\"\$@"\" --"
#         $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
#         ## Install more MSYS2 packages from https://packages.msys2.org/base here
#         taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
#         export PATH=/C/tools/msys64/mingw64/bin:$PATH
#         export MAKE=mingw32-make  # so that Autotools can find it
#         ;;
#     esac

# before_cache:
# - |-
#     case $TRAVIS_OS_NAME in
#       windows)
#         # https://unix.stackexchange.com/a/137322/107554
#         $msys2 pacman --sync --clean --noconfirm
#         ;;
#     esac

# cache:
#     directories:
#     - $HOME/AppData/Local/Temp/chocolatey
#     - /C/tools/msys64

script:
  # - taskkill -IM "gpg-agent.exe" -F
  # - export KITCHEN_LOCAL_YAML=.kitchen.proxy.yml
  - ruby -v
  # - gem install bundler
  - bundle install || bundle install || bundle install
  # - bundle exec docker version
  - bundle exec kitchen --version
  # - bundle exec rake spec
  - bundle exec kitchen list
  - bundle exec kitchen test
    # - bundle exec kitchen test -d always

# script:
  # # - taskkill -IM "gpg-agent.exe" -F
  # # - powershell -ExecutionPolicy Bypass -NoLogo -File docker.ps1
  # - export KITCHEN_YAML=.kitchen.docker.yml
  # - ruby -v
  # - gem install bundler
  # - bundle install
  # - bundle exec docker version
  # - bundle exec kitchen --version
  # - bundle exec rake spec
  # - bundle exec kitchen test -d always

# script:
#   - docker version
#   - docker images
#   - docker info
#   # - docker run mcr.microsoft.com/windows/nanoserver:1803 ipconfig
#   - docker run mcr.microsoft.com/windows/servercore:1803 ipconfig